Installation
================

To install the module, please run the following command in your Python virtual environment:

.. code-block:: bash

   pip install crudcreator


Getting Started
==================

For a quick start, please check out : https://www.crudcreator.com/tutorial/getting-started


Tutorial
==================

To learn how to use crudcreator, please check out : https://www.crudcreator.com/tutorial


Documentation
==================

To access the documentation, please follow : https://www.crudcreator.com/documentation


Source
==================

To access the source, please follow : https://github.com/nedelab/crudcreator


License
==================

CRUDCreator is published under the MIT license.
Please check out : https://github.com/nedelab/crudcreator/tree/master/LICENSE


Contributing
==================

If you would like to contribute to the project, thank you! I'll let you refer to the following document: https://www.crudcreator.com/contributing